blank_issues_enabled: false
contact_links:
  - name: PentAGI Discord
    url: https://discord.gg/2xrMh7qX6m
    about: Get community support
  - name: PentAGI Telegram
    url: https://t.me/+Ka9i6CNwe71hMWQy
    about: Chat with the team
